const test=require('node:test');const assert=require('node:assert/strict');
const migration=require('../backend/migrations/0010_create_daily_care_reports');
async function sql(){const calls=[];await migration.up({query:async(s)=>{calls.push(String(s));return{rows:[]};}});return calls.join('\n');}
test('migration 0010 creates daily reports, typed items, vital links and append-only events',async()=>{const source=await sql();assert.equal(migration.version,'0010');
  for(const table of ['daily_care_reports','daily_care_items','daily_care_vital_links','daily_care_events'])assert.match(source,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));
  assert.match(source,/BEFORE UPDATE OR DELETE ON daily_care_items/);assert.match(source,/BEFORE UPDATE OR DELETE ON daily_care_events/);});
test('daily reports bind exact tenant subject and external provenance',async()=>{const source=await sql();assert.match(source,/FOREIGN KEY \(center_id, organization_id\)[\s\S]*organization_centers/);assert.match(source,/FOREIGN KEY \(integration_client_id, organization_id\)[\s\S]*integration_clients/);assert.match(source,/external_staff_id VARCHAR\(160\)[\s\S]*external_staff_display_name VARCHAR\(160\)/);assert.match(source,/uq_daily_external_record/);});
test('daily item schema supports approved categories without medical interpretation fields',async()=>{const source=await sql();for(const type of ['shift','nutrition','fluid_intake','sleep_rest','bowel_movement','urination','activity','mood_behavior','general_condition','symptom_note'])assert.match(source,new RegExp(`'${type}'`));assert.doesNotMatch(source,/diagnosis|severity|clinical_interpretation|recommendation/i);});
test('daily values are exactly one of text, numeric or boolean and preserve source units',async()=>{const source=await sql();assert.match(source,/value_type IN \('text','numeric','boolean'\)/);assert.match(source,/value_type='text'[\s\S]*numeric_value IS NULL[\s\S]*boolean_value IS NULL/);assert.match(source,/value_type='numeric' OR source_unit IS NULL/);});
test('daily history and relationship indexes are bounded-query ready and migration is additive',async()=>{const source=await sql();for(const name of ['idx_daily_care_profile_occurred','idx_daily_center_occurred','idx_daily_resident_occurred','idx_daily_items_report'])assert.match(source,new RegExp(name));assert.doesNotMatch(source,/ALTER TABLE (careProfiles|residents|centers)|DROP TABLE (?!IF EXISTS daily_)/i);});
