process.env.NODE_ENV='test';process.env.ALLOW_INSECURE_LINE_HEADER='true';const test=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const express=require('express');const fs=require('node:fs');const path=require('node:path');const db=require('../backend/db');const {createDailyCareRouter}=require('../backend/routes/dailyCare');
async function withApi(service,fn){db.resetAll();await db.Centers.insert({center_id:'CTR-A',status:'active'});await db.CenterStaff.insert({staff_id:'S1',center_id:'CTR-A',line_user_id:'U-STAFF',role:'staff',status:'active'});await db.CenterStaff.insert({staff_id:'S2',center_id:'CTR-A',line_user_id:'U-MANAGER',role:'manager',status:'active'});const app=express();app.use(express.json());app.locals.dailyCareService=service;app.use('/api',createDailyCareRouter());const server=http.createServer(app);await new Promise(r=>server.listen(0,r));const request=(route,options={},user='U-STAFF')=>fetch(`http://127.0.0.1:${server.address().port}${route}`,{...options,headers:{'Content-Type':'application/json',...(user?{'X-Line-User-Id':user}:{}),...(options.headers||{})}});try{await fn(request);}finally{await new Promise(r=>server.close(r));}}
function service(overrides={}){return{async listHistory(){return{items:[],nextCursor:null};},async listCenterWorkflow(){return{items:[],role:'manager'};},async recordNative(){return{duplicate:false,item:{dailyReportId:'DCR-1'}};},async returnForCorrection(){return{dailyReportId:'DCR-1',status:'changes_requested'};},async resubmitReport(){return{item:{dailyReportId:'DCR-2',status:'submitted'}};},async finalizeReport(){return{item:{dailyReportId:'DCR-1',status:'finalized'},notification:{notificationStatus:'queued'}};},async createCorrectionVersion(){return{duplicate:false,item:{dailyReportId:'DCR-2',status:'submitted'}};},async voidReport(){return{dailyReportId:'DCR-1',status:'voided'};},...overrides};}
test('daily routes require authenticated identity',async()=>withApi(service(),async request=>{assert.equal((await request('/api/care-profile/CP-A/daily-care',{},null)).status,401);assert.equal((await request('/api/center/CTR-A/residents/RES-A/daily-care',{method:'POST',body:'{}'},null)).status,401);}));
test('native route derives actor and subject while rejecting unknown or client-authoritative identity fields',async()=>{let seen;await withApi(service({async recordNative(x){seen=x;return{duplicate:false,item:{dailyReportId:'DCR-1'}};}}),async request=>{const rejected=await request('/api/center/CTR-A/residents/RES-A/daily-care',{method:'POST',body:JSON.stringify({occurredAt:'2026-08-27T01:00:00Z',items:[{itemType:'symptom_note',valueType:'text',textValue:'สบายดี'}],careProfileId:'CP-EVIL'})});assert.equal(rejected.status,400);const response=await request('/api/center/CTR-A/residents/RES-A/daily-care',{method:'POST',body:JSON.stringify({occurredAt:'2026-08-27T01:00:00Z',items:[{itemType:'symptom_note',valueType:'text',textValue:'สบายดี'}],vitalSigns:null})});assert.equal(response.status,201);});assert.deepEqual(seen,{lineUserId:'U-STAFF',centerId:'CTR-A',residentId:'RES-A',occurredAt:'2026-08-27T01:00:00Z',careDate:null,shift:null,items:[{itemType:'symptom_note',valueType:'text',textValue:'สบายดี'}],vitalSigns:null});});
test('history uses Care Profile scope and manager-only void enforcement',async()=>{let history;let voids=0;await withApi(service({async listHistory(x){history=x;return{items:[]};},async voidReport(){voids++;return{status:'voided'};}}),async request=>{assert.equal((await request('/api/care-profile/CP-A/daily-care?limit=5',{},'U-OWNER')).status,200);assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/void',{method:'POST',body:JSON.stringify({reason:'ผิด'})},'U-STAFF')).status,403);assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/void',{method:'POST',body:JSON.stringify({reason:'ผิด'})},'U-MANAGER')).status,200);});assert.equal(history.careProfileId,'CP-A');assert.equal(history.lineUserId,'U-OWNER');assert.equal(voids,1);});
test('review, return, resubmit and finalize routes preserve role boundaries',async()=>{const calls=[];await withApi(service({async listCenterWorkflow(x){calls.push(['list',x]);return{items:[]};},async returnForCorrection(x){calls.push(['return',x]);return{status:'changes_requested'};},async resubmitReport(x){calls.push(['resubmit',x]);return{item:{status:'submitted'}};},async finalizeReport(x){calls.push(['finalize',x]);return{item:{status:'finalized'}};}}),async request=>{
  assert.equal((await request('/api/center/CTR-A/daily-care/review?status=submitted')).status,200);
  assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/finalize',{method:'POST',body:'{}'})).status,403);
  assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/return',{method:'POST',body:JSON.stringify({reason:'แก้ไข'})},'U-MANAGER')).status,200);
  assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/resubmit',{method:'POST',body:JSON.stringify({occurredAt:'2026-08-27T01:00:00Z',items:[]})})).status,201);
  assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/finalize',{method:'POST',body:'{}'},'U-MANAGER')).status,200);
});assert.deepEqual(calls.map((item)=>item[0]),['list','return','resubmit','finalize']);});
test('finalized correction route is manager-only and forwards only explicit reason',async()=>{let seen;await withApi(service({async createCorrectionVersion(input){seen=input;return{duplicate:false,item:{status:'submitted'}};}}),async request=>{
  assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/corrections',{method:'POST',body:JSON.stringify({reason:'แก้ไข',centerId:'CTR-EVIL'})},'U-STAFF')).status,403);
  assert.equal((await request('/api/center/CTR-A/daily-care/DCR-1/corrections',{method:'POST',body:JSON.stringify({reason:'แก้ไข',centerId:'CTR-EVIL'})},'U-MANAGER')).status,201);
});assert.deepEqual(seen,{lineUserId:'U-MANAGER',centerId:'CTR-A',dailyReportId:'DCR-1',reason:'แก้ไข'});});
test('daily route failures use safe envelope without SQL or identifiers',async()=>withApi(service({async listHistory(){throw new Error('SELECT line_user_id FROM secret U-X');}}),async request=>{const response=await request('/api/care-profile/CP-A/daily-care',{},'U-OWNER');assert.equal(response.status,500);assert.doesNotMatch(JSON.stringify(await response.json()),/SELECT|line_user|U-X|stack/i);}));
test('production server mounts daily care in the existing backend app',()=>{const source=fs.readFileSync(path.resolve(__dirname,'..','backend','server.js'),'utf8');assert.match(source,/require\('\.\/routes\/dailyCare'\)/);assert.match(source,/app\.use\('\/api', createDailyCareRouter\(\)\)/);});
