const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const ui=require('../liff-app/family/consultation-ui');

const html=fs.readFileSync(path.join(__dirname,'..','liff-app','family','index.html'),'utf8');
const source=fs.readFileSync(path.join(__dirname,'..','liff-app','family','consultation-ui.js'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'..','liff-app','family','consultation-ui.css'),'utf8');
const NOW=new Date('2026-08-25T10:00:00Z');
const PROFILE=(id='CP-1',name='คุณแม่')=>({profile:{care_profile_id:id,patient_name:name}});
const ELIGIBLE={availability:'eligible',price:{amountMinor:10000,currency:'THB'},durationMinutes:1440,durationHours:24,termsVersion:'consult-terms-v1',checkoutAvailable:false};
const ACTIVE={caseId:'CASE-1',state:'active',waitingOn:'pharmacist',queuedAt:'2026-08-25T08:00:00Z',acceptedAt:'2026-08-25T09:00:00Z',expiresAt:'2026-08-26T09:00:00Z',effectiveClosed:false};
const QUEUED={caseId:'CASE-Q',state:'queued',waitingOn:'none',queuedAt:'2026-08-25T08:00:00Z',acceptedAt:null,expiresAt:null,effectiveClosed:false};
const RESOLVED={...ACTIVE,state:'resolved',waitingOn:'none'};
const CLOSED={...ACTIVE,state:'closed',waitingOn:'none',effectiveClosed:true,closedAt:'2026-08-26T09:00:00Z'};

function handler(pathValue){
  if(pathValue.startsWith('/api/consultations/eligibility'))return ELIGIBLE;
  if(pathValue.startsWith('/api/consultations?'))return {items:[]};
  throw Object.assign(new Error(pathValue),{errorCode:'UNMOCKED'});
}
function harness(custom=handler,options={}){
  const calls=[];let lastState;const scheduled=[];
  const request=async(pathValue,requestOptions={})=>{calls.push({path:pathValue,options:requestOptions});return custom(pathValue,requestOptions,calls.length);};
  const session=ui.createFamilyConsultationSession({request,onChange:(state)=>{lastState=state;},schedule:(callback,ms)=>{scheduled.push({callback,ms});return scheduled.length;},cancelSchedule:()=>{},cryptoApi:{randomUUID:()=> 'IDEMPOTENCY-1'},now:()=>NOW,...options});
  return {session,calls,scheduled,state:()=>lastState||session.snapshot()};
}

class FakeElement{constructor(tag='div'){this.tagName=tag;this.children=[];this.textContent='';this.className='';this.listeners={};this.type='';this.hidden=false;this.src='';}get firstChild(){return this.children[0]||null;}appendChild(child){this.children.push(child);return child;}removeChild(child){this.children.splice(this.children.indexOf(child),1);return child;}addEventListener(name,fn){this.listeners[name]=fn;}removeAttribute(name){if(name==='src')this.src='';}set innerHTML(_){throw new Error('innerHTML forbidden');}}
const fakeDocument=()=>({createElement:(tag)=>new FakeElement(tag)});
const walk=(node)=>[node.textContent,...node.children.flatMap(walk)].filter(Boolean);

test('consultation entry stays hidden when backend says unavailable',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?{availability:'unavailable',reasonCode:'CONSULTATION_DISABLED'}:{items:[]});await h.session.setProfile(PROFILE());assert.equal(h.state().visible,false);});
test('eligible selected Care Profile shows entry using server commercial metadata',async()=>{const h=harness();await h.session.setProfile(PROFILE());assert.equal(h.state().visible,true);assert.equal(h.state().eligibility.price.amountMinor,10000);assert.ok(h.calls[0].path.includes('careProfileId=CP-1'));});
test('switching Care Profile clears question case messages and ignores old clinical response',async()=>{let release;const pending=new Promise((resolve)=>{release=resolve;});const h=harness(async(pathValue)=>{if(pathValue.includes('CP-1')&&pathValue.includes('eligibility'))return pending;if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[]};});const old=h.session.setProfile(PROFILE('CP-1','คนแรก'));await h.session.setProfile(PROFILE('CP-2','คนใหม่'));release(ELIGIBLE);assert.deepEqual(await old,{ignored:true,stale:true});assert.equal(h.state().profileId,'CP-2');assert.equal(h.state().question,'');assert.equal(h.state().messages.length,0);});
test('emergency safety result blocks terms and payment progression',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'emergency_block',message:'ฉุกเฉิน'});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('หายใจไม่ออก');await h.session.checkQuestion();assert.equal(h.state().screen,'question');assert.match(h.state().statusMessage,/ฉุกเฉิน/);assert.equal(h.state().paymentStatus,null);});
test('unsupported medical scope cannot reach pricing terms and is not mislabeled as unrelated',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'medical_escalation'});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('อาการนี้คือโรคอะไร');await h.session.checkQuestion();assert.equal(h.state().screen,'question');assert.match(h.state().statusMessage,/แพทย์|บุคลากรทางการแพทย์/);assert.doesNotMatch(h.state().statusMessage,/ไม่เกี่ยวกับยา/);});
test('eligible question exposes a clear next step before fixed 100 THB terms',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'pharmacist_consultation_eligible'});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ควรหยุดยานี้ไหม');await h.session.checkQuestion();assert.equal(h.state().screen,'eligible');assert.match(html,/ไปต่อเพื่อปรึกษาเภสัชกร/);h.session.continueEligible();assert.equal(h.state().screen,'terms');assert.match(html,/100 บาท \/ 1 Consult Case/);assert.equal(h.state().eligibility.termsVersion,'consult-terms-v1');});
test('terms checkbox is mandatory before payment contract proceeds',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'pharmacist_consultation_eligible'});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ควรหยุดยานี้ไหม');await h.session.checkQuestion();h.session.continueEligible();h.session.acceptTerms(false);assert.deepEqual(await h.session.continueToPayment(),{ignored:true});h.session.acceptTerms(true);assert.equal((await h.session.continueToPayment()).status,'unavailable');});
test('missing backend terms version fails closed',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?{...ELIGIBLE,termsVersion:null}:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'pharmacist_consultation_eligible'});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ยา');await h.session.checkQuestion();assert.equal(h.state().screen,'eligible');assert.match(h.state().statusMessage,/ยังไม่ได้กำหนดเงื่อนไข/);assert.deepEqual(h.session.continueEligible(),{ignored:true});});
test('cancel before payment clears in-memory draft and makes no queue or checkout call',async()=>{const h=harness();await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ข้อมูลสุขภาพ');h.session.acceptTerms(true);h.session.cancelDraft();assert.equal(h.state().question,'');assert.equal(h.state().screen,'overview');assert.equal(h.calls.filter((call)=>call.path.includes('checkout')).length,0);});
test('production UI uses backend checkout without a fake-success control',()=>{assert.match(html,/กำลังเตรียมรายการชำระเงินอย่างปลอดภัย/);assert.match(html,/เริ่มปรึกษาเภสัชกร/);assert.doesNotMatch(html,/fake payment|mock payment|ชำระเงินสำเร็จจำลอง|ยืนยันว่าจ่ายแล้ว/i);assert.doesNotMatch(source,/markPaid|fakeSuccess/);assert.equal((html.match(/id="consultationEntry"/g)||[]).length,1);});
test('consultation action hierarchy separates the primary journey from history refresh and cancellation',()=>{assert.match(html,/consultation-primary-actions[\s\S]*เริ่มปรึกษาเภสัชกร/);assert.match(html,/consultation-history-header[\s\S]*รายการคำปรึกษาของฉัน[\s\S]*รีเฟรชรายการคำปรึกษา/);assert.match(html,/ตรวจคำถามและไปต่อ/);assert.match(html,/consultation-secondary-actions[\s\S]*consultation-cancel[\s\S]*ยกเลิกและล้างคำถาม/);assert.match(css,/consultation-secondary-actions\{margin-top:24px/);});
test('terms payment CTA is explicit without claiming payment success',()=>{assert.match(html,/ยอมรับเงื่อนไขและเข้าสู่การชำระเงิน/);assert.match(html,/PromptPay • 100 บาท/);assert.doesNotMatch(html,/ยืนยันว่าชำระเงินสำเร็จ|ชำระสำเร็จแล้ว/);});
test('injected payment harness supports confirming contract without a production payment control',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'pharmacist_consultation_eligible'},{checkoutAdapter:async(input)=>({status:'payment_confirming',termsVersion:input.termsVersion})});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ควรหยุดยานี้ไหม');await h.session.checkQuestion();h.session.continueEligible();h.session.acceptTerms(true);const result=await h.session.continueToPayment();assert.equal(result.status,'payment_confirming');assert.equal(result.termsVersion,'consult-terms-v1');assert.equal(h.state().paymentStatus,'payment_confirming');});
test('checkout is double-submit protected while backend checkout is pending',async()=>{let release;const pending=new Promise((resolve)=>{release=resolve;});const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'pharmacist_consultation_eligible'},{checkoutAdapter:async()=>pending});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ขอคำปรึกษาเรื่องยา');await h.session.checkQuestion();h.session.continueEligible();h.session.acceptTerms(true);const first=h.session.continueToPayment();assert.deepEqual(await h.session.continueToPayment(),{ignored:true});release({status:'payment_pending',orderId:'ORDER-1',payment:{qrImageUrl:'https://cdn.omise.co/qr.png'}});await first;});
test('stale checkout response cannot cross Care Profile switch or cancelled draft',async()=>{let releases=[];const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'pharmacist_consultation_eligible'},{checkoutAdapter:async()=>new Promise((resolve)=>releases.push(resolve))});await h.session.setProfile(PROFILE('CP-1','คนแรก'));h.session.openQuestion();h.session.setQuestion('คำถามเดิม');await h.session.checkQuestion();h.session.continueEligible();h.session.acceptTerms(true);const first=h.session.continueToPayment();await h.session.setProfile(PROFILE('CP-2','คนใหม่'));releases.shift()({status:'payment_pending',orderId:'ORDER-OLD',payment:{qrImageUrl:'https://cdn.omise.co/old.png'}});assert.deepEqual(await first,{ignored:true,stale:true});assert.equal(h.state().profileId,'CP-2');assert.equal(h.state().paymentOrderId,null);h.session.openQuestion();h.session.setQuestion('คำถามใหม่');await h.session.checkQuestion();h.session.continueEligible();h.session.acceptTerms(true);const second=h.session.continueToPayment();h.session.cancelDraft();releases.shift()({status:'payment_pending',orderId:'ORDER-CANCELLED'});assert.deepEqual(await second,{ignored:true,stale:true});assert.equal(h.state().screen,'overview');assert.equal(h.state().paymentOrderId,null);});
test('terminal payment state clears QR instructions and never starts consultation countdown',async()=>{const h=harness(async(pathValue)=>pathValue.includes('eligibility')?ELIGIBLE:pathValue.startsWith('/api/consultations?')?{items:[]}:{action:'pharmacist_consultation_eligible'},{checkoutAdapter:async()=>({status:'payment_pending',orderId:'ORDER-1',payment:{qrImageUrl:'https://cdn.omise.co/qr.png'}}),paymentStatusAdapter:async()=>({status:'failed'})});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ขอคำปรึกษาเรื่องยา');await h.session.checkQuestion();h.session.continueEligible();h.session.acceptTerms(true);await h.session.continueToPayment();assert.ok(h.state().paymentInstructions);await h.session.pollPaymentStatus('ORDER-1');assert.equal(h.state().paymentStatus,'failed');assert.equal(h.state().paymentInstructions,null);assert.equal(ui.remainingLabel({state:'queued',expiresAt:null},NOW),'');});
test('verified queued payment leaves payment flow and opens the persistent queued room',async()=>{const h=harness(async(pathValue)=>{if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[QUEUED]};if(pathValue==='/api/consultations/CASE-Q')return {...QUEUED,initialQuestion:'ขอคำปรึกษาเรื่องยา'};if(pathValue.includes('/CASE-Q/messages?'))return {items:[],nextSequence:0};return {action:'pharmacist_consultation_eligible'};},{checkoutAdapter:async()=>({status:'payment_pending',orderId:'ORDER-1',payment:{qrImageUrl:'https://cdn.omise.co/qr.png'}}),paymentStatusAdapter:async()=>({status:'queued',orderId:'ORDER-1',caseId:'CASE-Q'})});await h.session.setProfile(PROFILE());h.session.openQuestion();h.session.setQuestion('ขอคำปรึกษาเรื่องยา');await h.session.checkQuestion();h.session.continueEligible();h.session.acceptTerms(true);await h.session.continueToPayment();await h.session.pollPaymentStatus('ORDER-1');assert.equal(h.state().screen,'overview');assert.equal(h.state().paymentInstructions,null);assert.equal(h.state().paymentOrderId,null);assert.equal(h.state().selectedCase.caseId,'CASE-Q');assert.equal(h.state().selectedCase.initialQuestion,'ขอคำปรึกษาเรื่องยา');assert.equal(h.calls.filter((call)=>call.path.includes('/checkout')).length,0);});
test('Family reload lists an existing queued room without recreating checkout or showing draft cancellation',async()=>{let checkoutCalls=0;const h=harness(async(pathValue)=>{if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[QUEUED]};if(pathValue.includes('/checkout'))checkoutCalls+=1;});await h.session.setProfile(PROFILE());assert.equal(h.state().collections.queued[0].caseId,'CASE-Q');assert.equal(h.state().screen,'overview');assert.equal(h.state().paymentOrderId,null);assert.equal(checkoutCalls,0);assert.match(source,/el\.cancel\.hidden=state\.screen==='overview'\|\|state\.paymentStatus==='queued'/);});
test('QR renderer removes stale source and reliably hides terminal QR element',()=>{const image=new FakeElement('img');ui.renderPaymentQr(image,{qrImageUrl:'https://cdn.omise.co/qr.png'});assert.equal(image.hidden,false);assert.match(image.src,/cdn\.omise\.co/);ui.renderPaymentQr(image,null);assert.equal(image.hidden,true);assert.equal(image.src,'');assert.match(css,/\.consultation-payment__qr\[hidden\]\{display:none!important\}/);});
test('PromptPay QR accepts credential-free HTTPS only',()=>{assert.equal(ui.safePaymentQrUrl('javascript:alert(1)'),null);assert.equal(ui.safePaymentQrUrl('https://user:pass@example.com/qr'),null);assert.equal(ui.safePaymentQrUrl('http://cdn.omise.co/qr'),null);assert.equal(ui.safePaymentQrUrl('https://cdn.omise.co/qr'),'https://cdn.omise.co/qr');});
test('queued case has no countdown before pharmacist accepts',()=>{assert.equal(ui.remainingLabel({state:'queued',expiresAt:null},NOW),'');const groups=ui.categorizeCases([{caseId:'Q',state:'queued',queuedAt:NOW.toISOString()}]);assert.equal(groups.queued.length,1);assert.match(source,/ระยะเวลา 24 ชั่วโมงจะเริ่มเมื่อเภสัชกรรับเคส/);});
test('accepted case countdown derives only from backend expiresAt',()=>{assert.equal(ui.remainingLabel({...ACTIVE,expiresAt:'2026-08-25T17:42:00Z'},NOW),'เหลือเวลา 7 ชม. 42 นาที');});
test('message polling uses afterSequence and deduplicates deterministic results',async()=>{let poll=0;const h=harness(async(pathValue)=>{if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[]};if(pathValue==='/api/consultations/CASE-1')return ACTIVE;if(pathValue.includes('/messages?'))return ++poll===1?{items:[{sequence:2,body:'สอง'},{sequence:1,body:'หนึ่ง'}],nextSequence:2}:{items:[{sequence:2,body:'ซ้ำ'},{sequence:3,body:'สาม'}],nextSequence:3};});await h.session.setProfile(PROFILE());await h.session.selectCase('CASE-1');await h.session.pollOnce();assert.deepEqual(h.state().messages.map((item)=>item.sequence),[1,2,3]);assert.ok(h.calls.some((call)=>call.path.includes('afterSequence=2')));});
test('Family LIFF re-entry discovers the same active case and reloads persisted messages',async()=>{let checkoutCalls=0;const backend=async(pathValue)=>{if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[ACTIVE]};if(pathValue==='/api/consultations/CASE-1')return {...ACTIVE,initialQuestion:'คำถามเดิม'};if(pathValue.includes('/messages?'))return {items:[{sequence:2,senderType:'pharmacist',body:'คำตอบเดิม'},{sequence:1,senderType:'customer',body:'คำถามเดิม'}],nextSequence:2};if(pathValue.includes('/checkout')){checkoutCalls+=1;throw new Error('must not create');}};for(let visit=0;visit<2;visit+=1){const h=harness(backend);await h.session.setProfile(PROFILE());assert.equal(h.state().collections.active[0].caseId,'CASE-1');await h.session.selectCase('CASE-1');assert.deepEqual(h.state().messages.map((item)=>item.sequence),[1,2]);assert.equal(h.state().selectedCase.initialQuestion,'คำถามเดิม');}assert.equal(checkoutCalls,0);});
test('resolved consultation remains messageable until backend expiration',()=>{assert.equal(ui.canMessage(RESOLVED,NOW),true);assert.equal(ui.categorizeCases([RESOLVED]).resolved.length,1);assert.match(source,/ยังสามารถถามต่อเกี่ยวกับเคสนี้ได้จนถึงเวลาสิ้นสุด/);});
test('closed consultation is read-only while history remains renderable',()=>{assert.equal(ui.canMessage(CLOSED,NOW),false);assert.equal(ui.categorizeCases([CLOSED]).closed.length,1);assert.match(source,/การปรึกษานี้สิ้นสุดแล้ว/);});
test('Family and Pharmacist lifecycle labels preserve queued active resolved reopened and closed semantics',()=>{const lifecycle=[{state:'queued',expiresAt:null},{...ACTIVE,state:'active'},{...RESOLVED},{...ACTIVE,state:'active',waitingOn:'pharmacist'},{...CLOSED}];assert.deepEqual(lifecycle.map((item)=>ui.categorizeCases([item])).map((groups)=>Object.entries(groups).find(([,items])=>items.length)?.[0]),['queued','active','resolved','active','closed']);assert.equal(ui.paymentStatusLabel('queued'),'ชำระเงินแล้ว • รอเภสัชกรรับเคส');assert.match(ui.paymentStatusLabel('failed'),/ไม่สำเร็จ/);});
test('exact backend expiration disables both customer and pharmacist send semantics',()=>{const exact={...ACTIVE,expiresAt:NOW.toISOString()};assert.equal(ui.effectiveClosed(exact,NOW),true);assert.equal(ui.canMessage(exact,NOW),false);});
test('revoked caregiver denial clears sensitive local state without deleting backend records',async()=>{const h=harness(async(pathValue)=>{if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[ACTIVE]};throw Object.assign(new Error('private'),{errorCode:'CONSULTATION_ACCESS_DENIED'});});await h.session.setProfile(PROFILE());await h.session.selectCase('CASE-1');assert.match(h.state().statusMessage,/ไม่สามารถเข้าถึง/);assert.equal(h.state().selectedCase,null);assert.equal(h.state().messages.length,0);assert.equal(JSON.stringify(h.state()).includes('private'),false);});

test('polling can pause while document is hidden and resume without WebSocket',async()=>{const h=harness(async(pathValue)=>{if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[]};if(pathValue==='/api/consultations/CASE-1')return ACTIVE;if(pathValue.includes('/messages?'))return {items:[],nextSequence:0};});await h.session.setProfile(PROFILE());await h.session.selectCase('CASE-1');const before=h.scheduled.length;h.session.setDocumentVisible(false);h.session.setDocumentVisible(true);assert.equal(h.scheduled.length,before+1);assert.doesNotMatch(source,/WebSocket|EventSource/);});
test('message renderer treats HTML payload as text and labels only safe roles',()=>{const doc=fakeDocument(),container=new FakeElement(),payload='<script>window.pwned=true</script>';ui.renderMessages(doc,container,[{sequence:1,senderType:'customer',body:payload},{sequence:2,senderType:'pharmacist',body:'ตอบ'}]);assert.ok(walk(container).includes(payload));assert.match(walk(container).join('|'),/คุณ|เภสัชกร/);});
test('message send uses idempotency and prevents double submit',async()=>{let release;const pending=new Promise((resolve)=>{release=resolve;});const h=harness(async(pathValue,options)=>{if(pathValue.includes('eligibility'))return ELIGIBLE;if(pathValue.startsWith('/api/consultations?'))return {items:[]};if(pathValue==='/api/consultations/CASE-1')return ACTIVE;if(pathValue.includes('/messages?'))return {items:[],nextSequence:0};if(pathValue.endsWith('/messages'))return pending;});await h.session.setProfile(PROFILE());await h.session.selectCase('CASE-1');const first=h.session.sendMessage('คำถาม');assert.deepEqual(await h.session.sendMessage('ซ้ำ'),{ignored:true});const call=h.calls.find((item)=>item.path.endsWith('/messages'));assert.deepEqual(JSON.parse(call.options.body),{body:'คำถาม',idempotencyKey:'IDEMPOTENCY-1'});release({message:{sequence:1,senderType:'customer',body:'คำถาม'}});await first;});
test('privacy contract stores no consultation data in browser storage URL or logs',()=>{assert.doesNotMatch(source,/localStorage|sessionStorage/);assert.doesNotMatch(source,/history\.(pushState|replaceState)|location\.(search|hash)/);assert.doesNotMatch(source,/console\.(log|info|debug|error)\s*\(/);});
test('Family UI cannot render pharmacist assistant internals or write Care Profile',()=>{for(const forbidden of ['caseSummary','responseGuidance','questionsToAsk','AI Case Brief','updateCareProfileHealth','CareProfiles.update','medication write'])assert.equal(source.includes(forbidden),false,forbidden);assert.doesNotMatch(html,/AI Pharmacist Assistant|responseGuidance|questionsToAsk/);});
test('profile-scoped API sends only identifiers question and message allowlists',()=>{assert.match(source,/careProfileId:profileId,question/);assert.match(source,/body:text,idempotencyKey/);for(const forbidden of ['systemPrompt','providerOverride','modelOverride','healthContext'])assert.equal(source.includes(forbidden),false);});
test('Family consultation mobile and closed-history styles preserve readable content and touch targets',()=>{assert.match(css,/@media\(max-width:480px\)/);assert.match(css,/min-height:44px/);assert.match(css,/font-size:16px/);assert.match(css,/consultation-case--closed/);assert.match(css,/consultation-chat--closed/);assert.doesNotMatch(css,/consultation-message__body[^}]*color:\s*(#ccc|lightgray)/i);});
