process.env.NODE_ENV='test';
const test=require('node:test');const assert=require('node:assert/strict');
const {createIntegrationAdapterService}=require('../backend/services/integrationAdapterService');
const {createIntegrationAdapterMemoryRepository}=require('./helpers/integrationAdapterMemoryRepository');

const target='care.daily_report.finalized';
const native=(record='R-1')=>({center_code:'EXT-C',resident_id:'EXT-R',resident_name:'คุณยายตัวอย่าง',report_id:record,
  care_date:'2026-09-01',recorded_at:'2026-09-01T01:00:00Z',finalized_at:'2026-09-01T01:05:00Z',
  finalizer_name:'ผู้จัดการ',temperature:'36.7 C',note:'อาการทั่วไปปกติ'});
function careItemNative(record='R-1',itemType='symptom_note',value='อาการทั่วไปปกติ'){const payload=native(record);delete payload.note;payload.data={care_items:[{item_type:itemType,value_type:'text',value}]};return payload;}
function serializedTransactions(){const locks=new Map();return async(key,fn)=>{const previous=locks.get(key)||Promise.resolve();let release;const gate=new Promise((resolve)=>{release=resolve;});locks.set(key,previous.then(()=>gate));await previous;try{return await fn();}finally{release();}};}
function fixture(){const repository=createIntegrationAdapterMemoryRepository();let seq=0;const audits=[];const clients=new Map([
  ['INT-A',{integrationClientId:'INT-A',organizationId:'ORG-A',sourceSystem:'HHS',eventScopes:[target],credentialId:'INTK-A',centers:['CTR-A']}],
  ['INT-B',{integrationClientId:'INT-B',organizationId:'ORG-B',sourceSystem:'HHS',eventScopes:[target],credentialId:'INTK-B',centers:['CTR-B']}],
  ['INT-C',{integrationClientId:'INT-C',organizationId:'ORG-C',sourceSystem:'HHS',eventScopes:[target],credentialId:'INTK-C',centers:['CTR-C']}],
  ['INT-X',{integrationClientId:'INT-X',organizationId:'ORG-X',sourceSystem:'OtherVendor',eventScopes:[target],credentialId:'INTK-X',centers:['CTR-X']}],
]);const service=createIntegrationAdapterService({repository,platformService:{async inspectIntegrationClient(id){return clients.get(id);}},idFactory:(prefix)=>`${prefix}-${++seq}`,now:()=>new Date('2026-09-01T00:00:00Z'),withTransaction:serializedTransactions(),audit:async(action,actor,meta)=>audits.push({action,actor,meta})});return{repository,service,clients,audits};}
function rules(sample,{generalReportPath='note'}={}){const path=new Map(sample.fields.map((field)=>[field.sourcePath,field.locatorKey]));return[
  ['subject.externalCenterId','center_code'],['subject.externalResidentId','resident_id'],['subject.displayName','resident_name'],
  ['data.externalRecordId','report_id'],['data.careDate','care_date'],['data.recordedAt','recorded_at'],
  ['data.finalizedAt','finalized_at'],['data.finalizedBy.displayName','finalizer_name'],['vitals.temperature','temperature'],
  ['data.generalReport',generalReportPath],
].map(([targetField,source])=>({targetField,locatorKey:path.get(source)}));}
async function capture(f,clientId,payload=native()){await f.service.startCapture({integrationClientId:clientId,actorReference:'ADM'});await f.service.captureIfWaiting({identity:{integrationClientId:clientId,sourceSystem:f.clients.get(clientId).sourceSystem},input:payload});return(await f.service.getLatestSample({integrationClientId:clientId})).sample;}
async function commission(f,clientId='INT-A'){const sample=await capture(f,clientId);const draft=await f.service.createDraft({integrationClientId:clientId,sampleId:sample.sampleId,mappingRules:rules(sample),actorReference:'ADM'});await f.service.activateAdapter({integrationClientId:clientId,sampleId:sample.sampleId,adapterProfileId:draft.adapter.adapterVersionId,actorReference:'ADM'});return draft.adapter;}

test('first source sample creates reusable Template V1 and second same-source client reuses it',async()=>{const f=fixture();const first=await commission(f);assert.equal(first.version,1);assert.equal(f.repository.state.templates.length,1);assert.equal(f.repository.state.versions.length,1);assert.equal(f.repository.state.bindings.length,1);const sample=await capture(f,'INT-B');assert.equal(sample.reusableAdapters.length,1);assert.equal(sample.reusableAdapters[0].adapterTemplateId,first.adapterTemplateId);assert.equal(sample.reusableAdapters[0].exactFingerprint,true);await f.service.reuseAdapter({integrationClientId:'INT-B',sampleId:sample.sampleId,adapterVersionId:sample.reusableAdapters[0].adapterVersionId,actorReference:'ADM'});assert.equal(f.repository.state.templates.length,1);assert.equal(f.repository.state.bindings.filter((row)=>row.status==='active').length,2);});

test('care_items item_type locator fingerprints and reuses only an exact structure',async()=>{const f=fixture();const firstSample=await capture(f,'INT-A',careItemNative());const generalReportPath='data.care_items[item_type=symptom_note].value';const draft=await f.service.createDraft({integrationClientId:'INT-A',sampleId:firstSample.sampleId,mappingRules:rules(firstSample,{generalReportPath}),actorReference:'ADM'});await f.service.activateAdapter({integrationClientId:'INT-A',sampleId:firstSample.sampleId,adapterProfileId:draft.adapter.adapterVersionId,actorReference:'ADM'});const reusable=await capture(f,'INT-B',careItemNative('R-2','symptom_note','มีไข้ต่ำ'));assert.equal(reusable.reusableAdapters.length,1);assert.equal(reusable.reusableAdapters[0].exactFingerprint,true);await f.service.reuseAdapter({integrationClientId:'INT-B',sampleId:reusable.sampleId,adapterVersionId:reusable.reusableAdapters[0].adapterVersionId,actorReference:'ADM'});const rulesStored=f.repository.state.versions[0].mapping_rules;const generalRule=rulesStored.find((item)=>item.targetField==='data.generalReport');assert.deepEqual(generalRule.locators[0].where,{field:'item_type',equals:'symptom_note'});const changed=await capture(f,'INT-C',careItemNative('R-3','activity_note','เดินเล่น'));assert.equal(changed.reusableAdapters.length,0);});

test('reuse requires an exact structural fingerprint even when all existing mapped fields remain compatible',async()=>{const f=fixture();const first=await commission(f);const sample=await capture(f,'INT-B',{...native('R-EXTRA'),new_optional_field:'new'});assert.equal(sample.reusableAdapters.length,0);await assert.rejects(f.service.reuseAdapter({integrationClientId:'INT-B',sampleId:sample.sampleId,adapterVersionId:first.adapterVersionId,actorReference:'ADM'}),{code:'ADAPTER_REUSE_NOT_AVAILABLE'});assert.equal(f.repository.state.bindings.filter((row)=>row.integration_client_id==='INT-B'&&row.status==='active').length,0);});

test('same source/event/shape cannot create duplicate template while first V1 is still draft',async()=>{const f=fixture();const first=await capture(f,'INT-A');const second=await capture(f,'INT-B');await f.service.createDraft({integrationClientId:'INT-A',sampleId:first.sampleId,mappingRules:rules(first),actorReference:'ADM-A'});await assert.rejects(f.service.createDraft({integrationClientId:'INT-B',sampleId:second.sampleId,mappingRules:rules(second),actorReference:'ADM-B'}),{code:'ADAPTER_TEMPLATE_COMMISSIONING_IN_PROGRESS'});assert.equal(f.repository.state.templates.length,1);});

test('payload value changes process normally and extra unused field creates one actionable notice',async()=>{const f=fixture();await commission(f);const identity={integrationClientId:'INT-A',sourceSystem:'HHS'};const changed=native('R-2');changed.resident_name='คุณตาตัวอย่าง';changed.temperature='36.8 C';let result=await f.service.prepareInbound({identity,input:changed});assert.equal(result.action,'transformed');assert.equal(f.repository.state.notices.length,0);changed.blood_glucose=101;result=await f.service.prepareInbound({identity,input:changed});assert.equal(result.action,'transformed');await f.service.prepareInbound({identity,input:{...changed,report_id:'R-3'}});assert.equal(f.repository.state.notices.length,1);assert.equal(f.repository.state.notices[0].notice_type,'NEW_SOURCE_FIELDS_AVAILABLE');assert.equal(f.repository.state.notices[0].occurrence_count,2);});

test('ignored new field memory prevents repeated notices across events and later Adapter versions',async()=>{const f=fixture();await commission(f);const identity={integrationClientId:'INT-A',sourceSystem:'HHS'};const changed={...native(),device_id:'DEVICE-1'};await f.service.prepareInbound({identity,input:changed});let status=await f.service.getAdapterStatus({integrationClientId:'INT-A'});assert.equal(status.notices.length,1);await f.service.updateNotice({integrationClientId:'INT-A',noticeId:status.notices[0].noticeId,status:'ignored',actorReference:'ADM'});await f.service.prepareInbound({identity,input:{...changed,report_id:'R-2',device_id:'DEVICE-2'}});const sample=await capture(f,'INT-A',native('R-V2'));const draft=await f.service.createDraft({integrationClientId:'INT-A',sampleId:sample.sampleId,mappingRules:rules(sample),actorReference:'ADM'});await f.service.activateAdapter({integrationClientId:'INT-A',sampleId:sample.sampleId,adapterProfileId:draft.adapter.adapterVersionId,actorReference:'ADM'});await f.service.prepareInbound({identity,input:{...changed,report_id:'R-3',device_id:'DEVICE-3'}});status=await f.service.getAdapterStatus({integrationClientId:'INT-A'});assert.equal(status.notices.length,0);assert.equal(f.repository.state.notices.length,1);assert.equal(f.repository.state.notices[0].status,'ignored');assert.equal(f.repository.state.notices[0].adapter_version_id,draft.adapter.adapterVersionId);});

test('mapped required disappearance or incompatible type blocks without automatic remapping',async()=>{const f=fixture();await commission(f);const identity={integrationClientId:'INT-A',sourceSystem:'HHS'};const missing=native();delete missing.report_id;missing.report_identifier='R-1';await assert.rejects(f.service.prepareInbound({identity,input:missing}),{code:'ADAPTER_SOURCE_CHANGED'});const primitiveType=native();primitiveType.temperature=36.7;await assert.rejects(f.service.prepareInbound({identity,input:primitiveType}),{code:'ADAPTER_SOURCE_CHANGED'});const incompatible=native();incompatible.temperature={numeric:36.7};await assert.rejects(f.service.prepareInbound({identity,input:incompatible}),{code:'ADAPTER_SOURCE_CHANGED'});const unknownUnit=native();unknownUnit.temperature='98.6 F';await assert.rejects(f.service.prepareInbound({identity,input:unknownUnit}),{code:'ADAPTER_SOURCE_CHANGED'});assert.equal(f.repository.state.versions.length,1);assert.equal(f.repository.state.notices.some((row)=>row.notice_type==='ADAPTER_SOURCE_CHANGED'),true);});

test('editing creates V2 draft, activation is atomic for bindings, and rollback affects future events only',async()=>{const f=fixture();const v1=await commission(f);let sample=await capture(f,'INT-B');await f.service.reuseAdapter({integrationClientId:'INT-B',sampleId:sample.sampleId,adapterVersionId:v1.adapterVersionId,actorReference:'ADM'});sample=await capture(f,'INT-A',{...native('R-EDIT'),new_note_field:'unused'});const draft=await f.service.createDraft({integrationClientId:'INT-A',sampleId:sample.sampleId,mappingRules:rules(sample),actorReference:'ADM'});assert.equal(draft.adapter.version,2);let status=await f.service.getAdapterStatus({integrationClientId:'INT-A'});assert.equal(status.activeAdapter.version,1);assert.equal(status.versions.find((item)=>item.version===2).status,'draft');await f.service.activateAdapter({integrationClientId:'INT-A',sampleId:sample.sampleId,adapterProfileId:draft.adapter.adapterVersionId,actorReference:'ADM'});assert.equal((await f.service.getAdapterStatus({integrationClientId:'INT-B'})).activeAdapter.version,2);assert.equal(f.repository.state.bindings.filter((row)=>row.status==='active').every((row)=>row.adapter_version_id===draft.adapter.adapterVersionId),true);const historyBefore=JSON.stringify(f.repository.state);await f.service.rollbackAdapter({integrationClientId:'INT-A',adapterVersionId:v1.adapterVersionId,actorReference:'ADM'});status=await f.service.getAdapterStatus({integrationClientId:'INT-B'});assert.equal(status.activeAdapter.version,1);assert.equal(JSON.parse(historyBefore).versions.length,f.repository.state.versions.length);const rollbackAudit=f.audits.find((item)=>item.action==='integration.adapter_rolled_back');assert.equal(rollbackAudit.meta.adapterTemplateId,v1.adapterTemplateId);assert.deepEqual(Object.keys(rollbackAudit.meta).sort(),['adapterTemplateId','adapterVersionId','version']);});

test('concurrent draft, activation, binding and source-notice operations converge under one template lock',async()=>{const f=fixture();const v1=await commission(f);const sampleA=await capture(f,'INT-A',native('R-DRAFT-A'));const sampleB=await capture(f,'INT-A',native('R-DRAFT-B'));const [draftA,draftB]=await Promise.all([
  f.service.createDraft({integrationClientId:'INT-A',sampleId:sampleA.sampleId,mappingRules:rules(sampleA),actorReference:'ADM-A'}),
  f.service.createDraft({integrationClientId:'INT-A',sampleId:sampleB.sampleId,mappingRules:rules(sampleB),actorReference:'ADM-B'}),
]);assert.deepEqual(new Set([draftA.adapter.version,draftB.adapter.version]),new Set([2,3]));await Promise.all([
  f.service.activateAdapter({integrationClientId:'INT-A',sampleId:sampleA.sampleId,adapterProfileId:draftA.adapter.adapterVersionId,actorReference:'ADM-A'}),
  f.service.activateAdapter({integrationClientId:'INT-A',sampleId:sampleA.sampleId,adapterProfileId:draftA.adapter.adapterVersionId,actorReference:'ADM-B'}),
]);assert.equal(f.repository.state.versions.filter((row)=>row.status==='active').length,1);const [reuseB,reuseC]=await Promise.all(['INT-B','INT-C'].map(async(clientId)=>{const sample=await capture(f,clientId);return f.service.reuseAdapter({integrationClientId:clientId,sampleId:sample.sampleId,adapterVersionId:draftA.adapter.adapterVersionId,actorReference:'ADM'});}));assert.ok(reuseB.binding&&reuseC.binding);assert.equal(f.repository.state.bindings.filter((row)=>row.status==='active').length,3);const identity={integrationClientId:'INT-A',sourceSystem:'HHS'};await Promise.all([
  f.service.prepareInbound({identity,input:{...native('R-NOTICE-1'),device_id:'D-1'}}),
  f.service.prepareInbound({identity,input:{...native('R-NOTICE-2'),device_id:'D-2'}}),
]);assert.equal(f.repository.state.notices.filter((row)=>row.notice_type==='NEW_SOURCE_FIELDS_AVAILABLE').length,1);assert.equal(f.repository.state.notices.find((row)=>row.notice_type==='NEW_SOURCE_FIELDS_AVAILABLE').occurrence_count,2);await f.service.rollbackAdapter({integrationClientId:'INT-A',adapterVersionId:v1.adapterVersionId,actorReference:'ADM'});assert.equal(f.repository.state.versions.filter((row)=>row.status==='active').length,1);assert.equal(f.repository.state.bindings.filter((row)=>row.status==='active').every((row)=>row.adapter_version_id===v1.adapterVersionId),true);});

test('template shares only transformation knowledge and never client scope, credential, identity, or tenant access',async()=>{const f=fixture();const v1=await commission(f);const sample=await capture(f,'INT-B');await f.service.reuseAdapter({integrationClientId:'INT-B',sampleId:sample.sampleId,adapterVersionId:v1.adapterVersionId,actorReference:'ADM'});const serialized=JSON.stringify(f.repository.state.templates)+JSON.stringify(f.repository.state.versions);assert.doesNotMatch(serialized,/INTK-|ORG-|CTR-/);const a=await f.service.prepareInbound({identity:{integrationClientId:'INT-A',sourceSystem:'HHS'},input:native('A-1')});const b=await f.service.prepareInbound({identity:{integrationClientId:'INT-B',sourceSystem:'HHS'},input:native('B-1')});assert.notEqual(a.input.eventId,b.input.eventId);assert.equal(f.repository.state.bindings.find((row)=>row.integration_client_id==='INT-A').adapter_template_id,f.repository.state.bindings.find((row)=>row.integration_client_id==='INT-B').adapter_template_id);const otherSample=await capture(f,'INT-X');assert.equal(otherSample.reusableAdapters.length,0);});

test('revoked client cannot mutate shared Adapter while another client binding, Template and Versions remain intact',async()=>{const f=fixture();const v1=await commission(f);let sample=await capture(f,'INT-B');await f.service.reuseAdapter({integrationClientId:'INT-B',sampleId:sample.sampleId,adapterVersionId:v1.adapterVersionId,actorReference:'ADM'});sample=await capture(f,'INT-A',native('A-PENDING'));f.clients.get('INT-A').status='revoked';const before={templates:f.repository.state.templates.length,versions:f.repository.state.versions.length,binding:JSON.stringify(f.repository.state.bindings.find((row)=>row.integration_client_id==='INT-B'&&row.status==='active'))};await assert.rejects(f.service.startCapture({integrationClientId:'INT-A',actorReference:'ADM'}),{code:'REVOKED_CLIENT_TERMINAL'});await assert.rejects(f.service.createDraft({integrationClientId:'INT-A',sampleId:sample.sampleId,mappingRules:rules(sample),actorReference:'ADM'}),{code:'REVOKED_CLIENT_TERMINAL'});await assert.rejects(f.service.rollbackAdapter({integrationClientId:'INT-A',adapterVersionId:v1.adapterVersionId,actorReference:'ADM'}),{code:'REVOKED_CLIENT_TERMINAL'});assert.equal(f.repository.state.templates.length,before.templates);assert.equal(f.repository.state.versions.length,before.versions);assert.equal(JSON.stringify(f.repository.state.bindings.find((row)=>row.integration_client_id==='INT-B'&&row.status==='active')),before.binding);assert.equal((await f.service.getAdapterStatus({integrationClientId:'INT-B'})).activeAdapter.version,1);});
