process.env.NODE_ENV='test';
const test=require('node:test');const assert=require('node:assert/strict');
const adapter=require('../backend/domain/integrationAdapter');

function sample(){return{branch:{code:'HHS-01'},resident:{id:'RES-9',first_name:'สมชาย',last_name:'ใจดี',full_name:'สมชาย ใจดี'},report:{id:'RPT-77',date:'01/09/2569',recorded_at:'2026-09-01T01:00:00Z',finalized_at:'2026-09-01T01:05:00Z',note:'พักผ่อนได้'},finalizer:{id:'MGR-1',name:'ผู้จัดการ'},vitals:[{type:'temperature',value:'37.5c',unit:'C'},{type:'pulse',value:78,unit:'bpm'}],unused:{age:80,phone:'0812345678'},password:'do-not-store'};}
function find(fields,path){const field=fields.find((item)=>item.sourcePath===path);assert.ok(field,`missing ${path}`);return field;}
function rules(fields,{generalReportPath='report.note'}={}){const pair=(target,path)=>({targetField:target,locatorKey:find(fields,path).locatorKey});return[
  pair('subject.externalCenterId','branch.code'),pair('subject.externalResidentId','resident.id'),pair('subject.displayName','resident.full_name'),
  pair('data.externalRecordId','report.id'),pair('data.careDate','report.date'),pair('data.recordedAt','report.recorded_at'),pair('data.finalizedAt','report.finalized_at'),
  pair('data.finalizedBy.externalStaffId','finalizer.id'),pair('data.finalizedBy.displayName','finalizer.name'),pair('data.generalReport',generalReportPath),
  pair('vitals.temperature','vitals[type=temperature].value'),pair('vitals.pulse','vitals[type=pulse].value'),
];}

test('sample safety bounds and redacts secret-like values before persistence',()=>{const safe=adapter.sanitizeSample(sample());assert.equal(safe.payload.password,null);assert.doesNotMatch(JSON.stringify(safe.payload),/do-not-store/);assert.equal(safe.structuralFingerprint.length,64);assert.throws(()=>adapter.sanitizeSample({constructor:{x:1}}),{code:'ADAPTER_UNSAFE_SOURCE_KEY'});let deep={};let cursor=deep;for(let i=0;i<10;i++){cursor.next={};cursor=cursor.next;}assert.throws(()=>adapter.sanitizeSample(deep),{code:'ADAPTER_SAMPLE_TOO_DEEP'});assert.throws(()=>adapter.sanitizeSample({large:'x'.repeat(adapter.MAX_SAMPLE_BYTES)}),{code:'ADAPTER_SAMPLE_TOO_LARGE'});assert.throws(()=>adapter.sanitizeSample({items:Array.from({length:adapter.MAX_ARRAY_ITEMS+1},(_,index)=>index)}),{code:'ADAPTER_SAMPLE_ARRAY_TOO_LARGE'});assert.throws(()=>adapter.sanitizeSample(Object.fromEntries(Array.from({length:adapter.MAX_FIELDS+1},(_,index)=>[`field_${index}`,index]))),{code:'ADAPTER_SAMPLE_FIELD_LIMIT'});});
test('field discovery uses stable object locators and discriminator array selectors, never array indexes',()=>{const fields=adapter.discoverFields(adapter.sanitizeSample(sample()).payload);assert.equal(find(fields,'resident.full_name').valuePreview,'สมชาย ใจดี');const temperature=find(fields,'vitals[type=temperature].value');assert.equal(temperature.unitPreview,'C');assert.doesNotMatch(JSON.stringify(temperature.locator),/\[0\]|"0"/);const nullField=adapter.discoverFields({optional:null})[0];assert.equal(nullField.selectable,false);assert.equal(nullField.valueType,'null');const unstable=adapter.discoverFields({items:[{value:1},{value:2}]});assert.equal(unstable[0].selectable,false);assert.equal(unstable[0].unstable,true);const ambiguous=adapter.discoverFields({items:[{type:'temperature',value:1},{type:'temperature',value:2}]});assert.equal(ambiguous[0].selectable,false);assert.equal(ambiguous[0].unstable,true);});
test('HHS care_items uses item_type as a stable exact discriminator',()=>{const fields=adapter.discoverFields({data:{care_items:[{item_type:'symptom_note',value_type:'text',value:'ทดสอบระบบ'}]}});const note=find(fields,'data.care_items[item_type=symptom_note].value');assert.equal(note.selectable,true);assert.equal(note.valuePreview,'ทดสอบระบบ');assert.equal(note.locator.kind,'array_match');assert.deepEqual(note.locator.where,{field:'item_type',equals:'symptom_note'});assert.doesNotMatch(JSON.stringify(note.locator),/\[0\]|"0"/);});
test('care_items maps symptom_note value to canonical general report',()=>{const payload=sample();delete payload.report.note;payload.data={care_items:[{item_type:'symptom_note',value_type:'text',value:'  พักผ่อนได้  '}]};const safe=adapter.sanitizeSample(payload).payload;const fields=adapter.discoverFields(safe);const mapping=adapter.validateMappingRules(rules(fields,{generalReportPath:'data.care_items[item_type=symptom_note].value'}),fields);const generalReport=mapping.find((item)=>item.targetField==='data.generalReport');assert.deepEqual(generalReport.locators[0].where,{field:'item_type',equals:'symptom_note'});const event=adapter.transformPayload({integrationClientId:'INT-HHS',rules:mapping,payload:safe});assert.deepEqual(event.data.careItems,[{itemType:'symptom_note',valueType:'text',value:'พักผ่อนได้'}]);});
test('unique item_type and itemType values are supported while duplicates remain unstable',()=>{const snake=adapter.discoverFields({care_items:[{item_type:'symptom_note',value:'พักผ่อนได้'},{item_type:'activity_note',value:'เดินเล่น'}]});assert.equal(find(snake,'care_items[item_type=symptom_note].value').selectable,true);assert.equal(find(snake,'care_items[item_type=activity_note].value').selectable,true);const camel=adapter.discoverFields({careItems:[{itemType:'symptom_note',value:'พักผ่อนได้'}]});assert.deepEqual(find(camel,'careItems[itemType=symptom_note].value').locator.where,{field:'itemType',equals:'symptom_note'});const duplicate=adapter.discoverFields({care_items:[{item_type:'symptom_note',value:'หนึ่ง'},{item_type:'symptom_note',value:'สอง'}]});assert.equal(duplicate.length,1);assert.equal(duplicate[0].selectable,false);assert.equal(duplicate[0].unstable,true);});
test('array discriminator allowlist preserves legacy keys and rejects name or generic code',()=>{for(const key of ['type','kind','measurement_type','measurementType']){const fields=adapter.discoverFields({items:[{[key]:'temperature',value:37}]});assert.deepEqual(find(fields,`items[${key}=temperature].value`).locator.where,{field:key,equals:'temperature'});}for(const key of ['name','code']){const fields=adapter.discoverFields({items:[{[key]:'first',value:1},{[key]:'second',value:2}]});assert.equal(fields.length,1);assert.equal(fields[0].selectable,false);assert.equal(fields[0].unstable,true);}});
test('object value locators retain deterministic sibling unit semantics',()=>{const payload={temperature:{value:98.6,unit:'F'},pulse:78,pulse_unit:'bpm'};const fields=adapter.discoverFields(payload);assert.deepEqual(find(fields,'temperature.value').locator.unitPath,['temperature','unit']);assert.equal(find(fields,'temperature.value').unitPreview,'F');assert.deepEqual(find(fields,'pulse').locator.unitPath,['pulse_unit']);assert.equal(adapter.extractLocator(payload,find(fields,'pulse').locator).unit,'bpm');});
test('auto-suggest is deterministic and mapping stores locators rather than sample literals',()=>{const fields=adapter.autoSuggest(adapter.discoverFields(adapter.sanitizeSample(sample()).payload));assert.equal(find(fields,'resident.full_name').suggestedTarget,'subject.displayName');assert.equal(find(fields,'vitals[type=temperature].value').suggestedTarget,'vitals.temperature');const normalized=adapter.validateMappingRules(rules(fields),fields);assert.doesNotMatch(JSON.stringify(normalized),/สมชาย|RPT-77|37\.5/);assert.equal(normalized.find((item)=>item.targetField==='vitals.temperature').locators[0].kind,'array_match');});
test('deterministic transform builds strict canonical Daily event with known units and stable derived event ID',()=>{const safe=adapter.sanitizeSample(sample()).payload;const fields=adapter.discoverFields(safe);const mapping=adapter.validateMappingRules(rules(fields),fields);const first=adapter.transformPayload({integrationClientId:'INT-HHS',rules:mapping,payload:safe});const changed=sample();changed.resident.full_name='สมหญิง รักดี';changed.vitals[0].value='36.8c';const second=adapter.transformPayload({integrationClientId:'INT-HHS',rules:mapping,payload:adapter.sanitizeSample(changed).payload});assert.equal(first.eventId,second.eventId);assert.equal(second.subject.displayName,'สมหญิง รักดี');assert.equal(second.data.observations[0].numericValue,36.8);assert.equal(second.data.observations[0].sourceUnit,'C');assert.equal(second.data.careItems[0].itemType,'symptom_note');assert.equal(second.occurredAt,second.data.finalizedAt);});
test('required target, duplicate target, unfamiliar units and source drift fail closed',()=>{const safe=adapter.sanitizeSample(sample()).payload;const fields=adapter.discoverFields(safe);assert.throws(()=>adapter.validateMappingRules(rules(fields).filter((item)=>item.targetField!=='data.externalRecordId'),fields),{code:'ADAPTER_REQUIRED_TARGET_MISSING'});assert.throws(()=>adapter.validateMappingRules([...rules(fields),rules(fields)[0]],fields),{code:'ADAPTER_DUPLICATE_TARGET'});const mapping=adapter.validateMappingRules(rules(fields),fields);const bad=sample();bad.vitals[0].unit='fahrenheit';assert.throws(()=>adapter.transformPayload({integrationClientId:'INT',rules:mapping,payload:adapter.sanitizeSample(bad).payload}),{code:'ADAPTER_UNIT_UNSUPPORTED'});delete bad.report.id;assert.throws(()=>adapter.transformPayload({integrationClientId:'INT',rules:mapping,payload:adapter.sanitizeSample(bad).payload}),{code:'ADAPTER_SOURCE_CHANGED'});});
test('scalar unit suffix and ambiguous or timezone-dependent dates fail closed',()=>{const scalar=sample();delete scalar.vitals[0].unit;scalar.vitals[0].value='98.6 F';const safe=adapter.sanitizeSample(scalar).payload;const fields=adapter.discoverFields(safe);const mapping=adapter.validateMappingRules(rules(fields),fields);assert.throws(()=>adapter.transformPayload({integrationClientId:'INT',rules:mapping,payload:safe}),{code:'ADAPTER_UNIT_UNSUPPORTED'});assert.throws(()=>adapter.normalizeDate('01/02/2026'),{code:'ADAPTER_DATE_INVALID'});assert.throws(()=>adapter.normalizeDatetime('2026-09-01T08:00:00'),{code:'ADAPTER_DATETIME_INVALID'});assert.equal(adapter.normalizeDate('01/09/2569'),'2026-09-01');assert.equal(adapter.normalizeDatetime('01/09/2569 08:15'),'2026-09-01T01:15:00.000Z');});
test('first plus last composition is supported without literal persistence',()=>{const safe=adapter.sanitizeSample(sample()).payload;const fields=adapter.discoverFields(safe);const base=rules(fields).filter((item)=>item.targetField!=='subject.displayName');base.push({targetField:'subject.displayName',locatorKeys:[find(fields,'resident.first_name').locatorKey,find(fields,'resident.last_name').locatorKey]});const mapping=adapter.validateMappingRules(base,fields);const event=adapter.transformPayload({integrationClientId:'INT',rules:mapping,payload:safe});assert.equal(event.subject.displayName,'สมชาย ใจดี');});
test('structural fingerprint excludes patient values but includes stable array discriminator structure',()=>{const first=sample();const second=sample();second.resident.full_name='สมหญิง รักดี';second.vitals[0].value='36.8c';assert.equal(adapter.sanitizeSample(first).structuralFingerprint,adapter.sanitizeSample(second).structuralFingerprint);second.vitals[0].type='body_temp';assert.notEqual(adapter.sanitizeSample(first).structuralFingerprint,adapter.sanitizeSample(second).structuralFingerprint);const unsafeArray=adapter.discoverFields({people:[{name:'สมชาย',value:1},{name:'สมหญิง',value:2}]});assert.equal(unsafeArray[0].unstable,true);});
test('care_items fingerprint ignores patient text but includes stable item_type identity',()=>{const first={data:{care_items:[{item_type:'symptom_note',value_type:'text',value:'พักผ่อนได้'}]}};const valueChanged={data:{care_items:[{item_type:'symptom_note',value_type:'text',value:'มีไข้ต่ำ'}]}};const discriminatorChanged={data:{care_items:[{item_type:'activity_note',value_type:'text',value:'พักผ่อนได้'}]}};assert.equal(adapter.sanitizeSample(first).structuralFingerprint,adapter.sanitizeSample(valueChanged).structuralFingerprint);assert.notEqual(adapter.sanitizeSample(first).structuralFingerprint,adapter.sanitizeSample(discriminatorChanged).structuralFingerprint);});
