process.env.NODE_ENV='test';
const test=require('node:test');const assert=require('node:assert/strict');
const {createIntegrationAdapterService}=require('../backend/services/integrationAdapterService');
const {createIntegrationAdapterMemoryRepository}=require('./helpers/integrationAdapterMemoryRepository');

const target='care.daily_report.finalized';
const native=()=>({center_code:'EXT-C',resident_id:'EXT-R',resident_name:'คุณยายตัวอย่าง',report_id:'R-1',care_date:'2026-09-01',recorded_at:'2026-09-01T01:00:00Z',finalized_at:'2026-09-01T01:05:00Z',finalizer_name:'ผู้จัดการ',temperature:'36.7 C',note:'อาการทั่วไปปกติ',ignored_phone:'0812345678',access_token:'private'});
function fixture(){const repository=createIntegrationAdapterMemoryRepository();let seq=0;const audits=[];const service=createIntegrationAdapterService({repository,platformService:{async inspectIntegrationClient(){return{integrationClientId:'INT-1',eventScopes:[target]};}},idFactory:(prefix)=>`${prefix}-${++seq}`,now:()=>new Date('2026-09-01T00:00:00Z'),withTransaction:async(k,fn)=>fn(),audit:async(action,actor,meta)=>audits.push({action,actor,meta})});return{repository,service,audits};}
function mappingFor(sample){const byPath=new Map(sample.fields.map((field)=>[field.sourcePath,field.locatorKey]));const pair=(targetField,path)=>({targetField,locatorKey:byPath.get(path)});return[pair('subject.externalCenterId','center_code'),pair('subject.externalResidentId','resident_id'),pair('subject.displayName','resident_name'),pair('data.externalRecordId','report_id'),pair('data.careDate','care_date'),pair('data.recordedAt','recorded_at'),pair('data.finalizedAt','finalized_at'),pair('data.finalizedBy.displayName','finalizer_name'),pair('vitals.temperature','temperature'),pair('data.generalReport','note')];}
test('authenticated active capture consumes one bounded sample without clinical processing or identity learning',async()=>{const f=fixture();await f.service.startCapture({integrationClientId:'INT-1',targetEventType:target,actorReference:'ADM-1'});const result=await f.service.prepareInbound({identity:{integrationClientId:'INT-1'},input:native()});assert.equal(result.action,'captured');assert.equal(result.result.status,'sample_captured');assert.equal(result.result.clinicalDataCreated,false);assert.equal(f.repository.state.samples[0].sample_payload.access_token,null);assert.doesNotMatch(JSON.stringify(f.audits),/private|คุณยาย|อาการทั่วไป|0812345678/);const next=await f.service.prepareInbound({identity:{integrationClientId:'INT-1'},input:{bad:'canonical'}});assert.equal(next.action,'canonical');});
test('capture is exact-client scoped and temporary projection never exposes raw payload',async()=>{const f=fixture();await f.service.startCapture({integrationClientId:'INT-1',actorReference:'ADM'});const other=await f.service.prepareInbound({identity:{integrationClientId:'INT-2'},input:native()});assert.equal(other.action,'canonical');await f.service.prepareInbound({identity:{integrationClientId:'INT-1'},input:native()});const latest=await f.service.getLatestSample({integrationClientId:'INT-1',actorReference:'ADM-VIEWER'});assert.equal(latest.sample.status,'captured');assert.ok(latest.sample.fields.length);assert.equal(Object.hasOwn(latest.sample,'samplePayload'),false);assert.doesNotMatch(JSON.stringify(latest),/private/);const view=f.audits.find((item)=>item.action==='integration.adapter_sample_viewed');assert.equal(view.actor,'ADM-VIEWER');assert.deepEqual(Object.keys(view.meta).sort(),['fieldCount','integrationClientId','sampleId','sampleSizeBytes','targetEventType']);assert.doesNotMatch(JSON.stringify(view),/คุณยาย|อาการทั่วไป|0812345678|private/);});
test('capture window and raw sample expire closed without clinical processing',async()=>{const f=fixture();await f.service.startCapture({integrationClientId:'INT-1',actorReference:'ADM'});f.repository.state.samples[0].capture_expires_at='2026-08-31T23:59:59.000Z';let result=await f.service.prepareInbound({identity:{integrationClientId:'INT-1'},input:native()});assert.equal(result.action,'canonical');assert.equal(f.repository.state.samples[0].status,'expired');await f.service.startCapture({integrationClientId:'INT-1',actorReference:'ADM'});await f.service.captureIfWaiting({identity:{integrationClientId:'INT-1'},input:native()});f.repository.state.samples[1].sample_expires_at='2026-08-31T23:59:59.000Z';result=await f.service.getLatestSample({integrationClientId:'INT-1'});assert.equal(result.sample,null);assert.equal(f.repository.state.samples[1].status,'expired');assert.equal(f.repository.state.samples[1].sample_payload,null);});
test('preview creates no clinical data and activation versions adapters atomically while clearing sample',async()=>{const f=fixture();await f.service.startCapture({integrationClientId:'INT-1',actorReference:'ADM'});await f.service.captureIfWaiting({identity:{integrationClientId:'INT-1'},input:native()});let sample=(await f.service.getLatestSample({integrationClientId:'INT-1'})).sample;const mapping=mappingFor(sample);const preview=await f.service.previewAdapter({integrationClientId:'INT-1',sampleId:sample.sampleId,mappingRules:mapping});assert.equal(preview.valid,true);assert.equal(f.repository.state.profiles.length,0);const draft=await f.service.createDraft({integrationClientId:'INT-1',sampleId:sample.sampleId,mappingRules:mapping,actorReference:'ADM'});let active=await f.service.activateAdapter({integrationClientId:'INT-1',sampleId:sample.sampleId,adapterProfileId:draft.adapter.adapterProfileId,actorReference:'ADM'});assert.equal(active.adapter.version,1);assert.equal(f.repository.state.samples[0].sample_payload,null);
  await f.service.startCapture({integrationClientId:'INT-1',actorReference:'ADM'});const changed=native();changed.report_id='R-2';await f.service.captureIfWaiting({identity:{integrationClientId:'INT-1'},input:changed});sample=(await f.service.getLatestSample({integrationClientId:'INT-1'})).sample;const draft2=await f.service.createDraft({integrationClientId:'INT-1',sampleId:sample.sampleId,mappingRules:mappingFor(sample),actorReference:'ADM'});assert.equal((await f.service.getAdapterStatus({integrationClientId:'INT-1'})).activeAdapter.version,1);active=await f.service.activateAdapter({integrationClientId:'INT-1',sampleId:sample.sampleId,adapterProfileId:draft2.adapter.adapterProfileId,actorReference:'ADM'});assert.equal(active.adapter.version,2);assert.equal(f.repository.state.profiles.find((row)=>row.version===1).status,'superseded');});
test('active adapter transforms future values, ignores extras, and missing mapped input does not remap',async()=>{const f=fixture();await f.service.startCapture({integrationClientId:'INT-1',actorReference:'ADM'});await f.service.captureIfWaiting({identity:{integrationClientId:'INT-1'},input:native()});const sample=(await f.service.getLatestSample({integrationClientId:'INT-1'})).sample;const draft=await f.service.createDraft({integrationClientId:'INT-1',sampleId:sample.sampleId,mappingRules:mappingFor(sample),actorReference:'ADM'});await f.service.activateAdapter({integrationClientId:'INT-1',sampleId:sample.sampleId,adapterProfileId:draft.adapter.adapterProfileId,actorReference:'ADM'});const next=native();next.report_id='R-99';next.resident_name='คุณตาตัวอย่าง';next.temperature='37.1 C';next.new_secret_clinical='ignored';const transformed=await f.service.prepareInbound({identity:{integrationClientId:'INT-1'},input:next});assert.equal(transformed.action,'transformed');assert.equal(transformed.adapterVersion,1);assert.equal(transformed.input.subject.displayName,'คุณตาตัวอย่าง');assert.equal(transformed.input.data.externalRecordId,'R-99');assert.doesNotMatch(JSON.stringify(transformed.input),/new_secret_clinical|ignored_phone/);delete next.report_id;await assert.rejects(f.service.prepareInbound({identity:{integrationClientId:'INT-1'},input:next}),{code:'ADAPTER_SOURCE_CHANGED'});});
