process.env.NODE_ENV='test';const test=require('node:test');const assert=require('node:assert/strict');const express=require('express');const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const {createIntegrationEventsRouter}=require('../backend/routes/integrationEvents');
async function withApi(service,fn,{operationalLogger=()=>{},rateLimiter}={}){const app=express();app.use(express.json());app.locals.integrationEventService=service;const requireIntegration=(req,res,next)=>{if(req.header('Authorization')!=='Bearer good')return res.status(401).json({error:'unauthorized'});req.integration={integrationClientId:'INT-A',organizationId:'ORG-A',sourceSystem:'trusted'};next();};app.use('/api/integrations/v1',createIntegrationEventsRouter({requireIntegration,operationalLogger,...(rateLimiter?{rateLimiter}:{})}));const server=http.createServer(app);await new Promise(r=>server.listen(0,r));const request=(body,token='good')=>fetch(`http://127.0.0.1:${server.address().port}/api/integrations/v1/events`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});try{await fn(request);}finally{await new Promise(r=>server.close(r));}}
test('integration event endpoint requires bearer integration identity',async()=>withApi({async ingest(){assert.fail();}},async request=>assert.equal((await request({},'bad')).status,401)));
test('pending-subject acceptance returns 202 while same-payload duplicate returns 200',async()=>{let call=0;await withApi({async ingest(){call++;return call===1?{eventId:'EV-1',status:'pending_subject_mapping',duplicate:false}:{eventId:'EV-1',status:'pending_subject_mapping',duplicate:true};}},async request=>{const accepted=await request({});assert.equal(accepted.status,202);assert.equal((await accepted.json()).status,'pending_subject_mapping');assert.equal((await request({})).status,200);});});
test('all commissioned-only ignored outcomes return deterministic HTTP 200 without accepted or stored state',async()=>{for(const status of ['ignored_center_not_commissioned','ignored_subject_name_missing','ignored_subject_unresolved','ignored_subject_ambiguous','ignored_resident_inactive','ignored_care_profile_not_ready','ignored_family_group_not_bound','ignored_mapping_conflict','ignored_client_scope_mismatch'])await withApi({async ingest(){return{status,accepted:false,stored:false};}},async request=>{const response=await request({});assert.equal(response.status,200);assert.deepEqual(await response.json(),{status,accepted:false,stored:false});});});
test('rejected payload is 422 with a safe reason and conflicting duplicate is terminal 409',async()=>{await withApi({async ingest(){return{eventId:'EV-1',status:'rejected',duplicate:false,error:{code:'CENTER_MAPPING_NOT_FOUND',message:'ไม่พบการเชื่อมสาขาสำหรับระบบภายนอกนี้',retryable:false,request_id:'iref_safe'}};}},async request=>{const response=await request({});assert.equal(response.status,422);const body=await response.json();assert.equal(body.error.code,'CENTER_MAPPING_NOT_FOUND');assert.equal(body.error.retryable,false);});const conflict=Object.assign(new Error('raw payload'),{code:'EVENT_ID_PAYLOAD_CONFLICT',status:409});await withApi({async ingest(){throw conflict;}},async request=>{const response=await request({});assert.equal(response.status,409);const body=await response.json();assert.equal(body.status,'rejected');assert.equal(body.error.code,'EVENT_ID_REUSED');assert.equal(body.error.retryable,false);assert.doesNotMatch(JSON.stringify(body),/raw payload|EVENT_ID_PAYLOAD_CONFLICT/);});});
test('malformed and invalid clinical events keep non-2xx safe errors instead of becoming ignored',async()=>{for(const failure of [Object.assign(new Error('raw schema'),{code:'INVALID_EVENT_ENVELOPE',status:400}),Object.assign(new Error('raw clinical'),{code:'UNSUPPORTED_UNIT',status:422}),Object.assign(new Error('forbidden'),{code:'EVENT_SCOPE_DENIED',status:403})])await withApi({async ingest(){throw failure;}},async request=>{const response=await request({});assert.equal(response.status,failure.status);const body=await response.json();assert.equal(body.status,'rejected');assert.equal(body.error.retryable,false);assert.doesNotMatch(JSON.stringify(body),/raw schema|raw clinical|forbidden/);});});
test('unexpected provider/database failure uses retryable safe response envelope',async()=>withApi({async ingest(){throw new Error('SELECT clinical payload line_user_id');}},async request=>{const response=await request({});assert.equal(response.status,500);const body=await response.json();assert.equal(body.status,'retrying');assert.equal(body.error.code,'TEMPORARY_PROCESSING_UNAVAILABLE');assert.equal(body.error.retryable,true);assert.match(body.error.request_id,/^iref_[a-f0-9]{16}$/);assert.doesNotMatch(JSON.stringify(body),/SELECT|clinical|line_user|stack/i);}));

test('Center mapping rejection returns the documented safe terminal response',async()=>{const error=Object.assign(new Error('mapping row CTR-SECRET absent'),{code:'EXTERNAL_CENTER_MAPPING_NOT_FOUND',status:422});await withApi({async ingest(){throw error;}},async request=>{const response=await request({});assert.equal(response.status,422);const body=await response.json();assert.deepEqual(Object.keys(body.error).sort(),['code','message','request_id','retryable']);assert.equal(body.error.code,'CENTER_MAPPING_NOT_FOUND');assert.equal(body.error.retryable,false);assert.doesNotMatch(JSON.stringify(body),/CTR-SECRET|EXTERNAL_CENTER/);});});

test('pre-inbox terminal rejection emits only safe operational metadata for request correlation',async()=>{const logs=[];const error=Object.assign(new Error('private payload room A201'),{code:'EXTERNAL_CENTER_MAPPING_NOT_FOUND',status:422});await withApi({async ingest(){throw error;}},async request=>{await request({clinical:'private payload'});},{operationalLogger:(event)=>logs.push(event)});assert.equal(logs.length,1);assert.equal(logs[0].code,'CENTER_MAPPING_NOT_FOUND');assert.equal(logs[0].retryable,false);assert.match(logs[0].requestId,/^iref_[a-f0-9]{16}$/);assert.doesNotMatch(JSON.stringify(logs),/private payload|A201|clinical/);});
test('authenticated Integration Client limiter uses its own domain and fails closed',async()=>{const calls=[];const limiter={async checkAndRecord(...args){calls.push(args);return{allowed:false,remaining:0,retryAfterMs:3000};}};await withApi({async ingest(){assert.fail('rate limit must run before ingestion');}},async request=>{const response=await request({});assert.equal(response.status,429);assert.equal(response.headers.get('retry-after'),'3');const body=await response.json();assert.equal(body.error.code,'RATE_LIMITED');},{rateLimiter:limiter});assert.deepEqual(calls[0].slice(0,1),['INT-A']);assert.equal(calls[0][3].domain,'integration_client');const unavailable={async checkAndRecord(){throw Object.assign(new Error('database secret'),{code:'RATE_LIMIT_STORE_UNAVAILABLE'});}};await withApi({async ingest(){assert.fail();}},async request=>{const response=await request({});assert.equal(response.status,503);const body=await response.json();assert.equal(body.error.code,'TEMPORARY_PROCESSING_UNAVAILABLE');assert.doesNotMatch(JSON.stringify(body),/database secret/);},{rateLimiter:unavailable});});
test('production server mounts generic integration events and retry scheduler',()=>{const source=fs.readFileSync(path.resolve(__dirname,'..','backend','server.js'),'utf8');assert.match(source,/\/api\/integrations\/v1', createIntegrationEventsRouter/);assert.match(source,/integrationEventService\.processDue\(\)/);});

test('processed and PHIMOR-owned durable duplicates remain accepted',async()=>{for(const state of ['processed','pending_subject_mapping','received','processing','retrying']){await withApi({async ingest(){return{eventId:`EV-${state}`,status:state,duplicate:true};}},async request=>{const response=await request({});assert.equal(response.status,200,state);assert.equal((await response.json()).duplicate,true);});}});

test('rejected and dead duplicates remain terminal instead of returning HTTP 200',async()=>{for(const state of ['rejected','dead']){await withApi({async ingest(){return{eventId:`EV-${state}`,status:state,duplicate:true,error:{code:state==='dead'?'PROCESSING_RETRY_EXHAUSTED':'INVALID_FINALIZED_RECORD',message:'ดำเนินการไม่ได้',retryable:false,request_id:'iref_safe'}};}},async request=>{const response=await request({});assert.equal(response.status,422,state);const body=await response.json();assert.equal(body.status,state);assert.equal(body.duplicate,true);assert.equal(body.error.retryable,false);});}});

test('lost original terminal response followed by same-payload retry stays terminal',async()=>{let calls=0;await withApi({async ingest(){calls+=1;return{eventId:'EV-LOST-TERMINAL',status:'rejected',duplicate:calls>1,error:{code:'INVALID_FINALIZED_RECORD',message:'ข้อมูล finalized record ไม่ถูกต้องตามสัญญา',retryable:false,request_id:'iref_lost'}};}},async request=>{const original=await request({});assert.equal(original.status,422);const replay=await request({});assert.equal(replay.status,422);const body=await replay.json();assert.equal(body.duplicate,true);assert.equal(body.status,'rejected');assert.equal(body.error.code,'INVALID_FINALIZED_RECORD');});});
