function clone(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value));}
function createIntegrationAdapterMemoryRepository({now=()=>new Date('2026-09-01T00:00:00.000Z')}={}){
  const state={samples:[],templates:[],versions:[],bindings:[],notices:[]};state.profiles=state.versions;
  const joined=(version)=>{if(!version)return null;const template=state.templates.find((item)=>item.adapter_template_id===version.adapter_template_id)||{};return{...version,...template,status:version.status,target_event_type:template.target_event_type||version.target_event_type,version_status:version.status,binding_count:state.bindings.filter((item)=>item.adapter_template_id===version.adapter_template_id&&item.status==='active').length};};
  return{state,
    async expireSessions(){const expired=state.samples.filter((row)=>(row.status==='waiting'&&new Date(row.capture_expires_at)<=now())||(row.status==='captured'&&new Date(row.sample_expires_at)<=now()));expired.forEach((row)=>{row.status='expired';row.sample_payload=null;});return clone(expired.map((row)=>({adapter_sample_id:row.adapter_sample_id})));},
    async cancelWaiting(clientId,target){const rows=state.samples.filter((row)=>row.integration_client_id===clientId&&row.target_event_type===target&&row.status==='waiting');rows.forEach((row)=>{row.status='cancelled';});return clone(rows);},
    async createCapture(r){const row={adapter_sample_id:r.sampleId,integration_client_id:r.integrationClientId,source_system_key:r.sourceSystemKey,target_event_type:r.targetEventType,status:'waiting',capture_expires_at:r.captureExpiresAt,sample_expires_at:null,sample_payload:null,source_structural_fingerprint:null,source_structure:null,sample_size_bytes:null,discovered_field_count:null,captured_at:null,created_by:r.createdBy,created_at:'2026-09-01T00:00:00.000Z',updated_at:'2026-09-01T00:00:00.000Z'};state.samples.push(row);return clone(row);},
    async findWaitingCapture(clientId){return clone(state.samples.find((row)=>row.integration_client_id===clientId&&row.status==='waiting'&&new Date(row.capture_expires_at)>now()));},
    async captureSample(r){const row=state.samples.find((item)=>item.adapter_sample_id===r.sampleId&&item.status==='waiting');if(!row)return null;Object.assign(row,{status:'captured',sample_payload:clone(r.payload),source_structural_fingerprint:r.fingerprint,source_structure:clone(r.sourceStructure),sample_size_bytes:r.sizeBytes,discovered_field_count:r.fieldCount,sample_expires_at:r.sampleExpiresAt,captured_at:'2026-09-01T00:01:00.000Z'});return clone(row);},
    async findSample(clientId,sampleId){return clone(state.samples.find((row)=>row.integration_client_id===clientId&&row.adapter_sample_id===sampleId));},
    async findLatestSample(clientId,target){return clone([...state.samples].reverse().find((row)=>row.integration_client_id===clientId&&row.target_event_type===target&&['waiting','captured'].includes(row.status)));},
    async createTemplate(r){const row={adapter_template_id:r.templateId,source_system_key:r.sourceSystemKey,source_system_label:r.sourceSystemLabel,target_event_type:r.targetEventType,lineage_fingerprint:r.fingerprint,display_name:r.displayName,status:'active',created_by:r.createdBy,created_at:'2026-09-01T00:02:00.000Z',updated_at:'2026-09-01T00:02:00.000Z'};state.templates.push(row);return clone(row);},
    async findTemplate(id){return clone(state.templates.find((row)=>row.adapter_template_id===id));},
    async findTemplateByLineage(source,target,fingerprint){return clone(state.templates.find((row)=>row.source_system_key===source&&row.target_event_type===target&&row.lineage_fingerprint===fingerprint));},
    async listReusableTemplates(source,target){return clone(state.versions.filter((row)=>row.status==='active').map(joined).filter((row)=>row.source_system_key===source&&row.target_event_type===target));},
    async nextVersion(templateId){return{version:1+Math.max(0,...state.versions.filter((row)=>row.adapter_template_id===templateId).map((row)=>row.version))};},
    async createDraft(r){const row={adapter_version_id:r.adapterVersionId,adapter_profile_id:r.adapterVersionId,adapter_template_id:r.templateId,version:r.version,status:'draft',mapping_rules:clone(r.mappingRules),source_structural_fingerprint:r.fingerprint,source_structure:clone(r.sourceStructure),created_by:r.createdBy,activated_by:null,activated_at:null,created_at:'2026-09-01T00:02:00.000Z',updated_at:'2026-09-01T00:02:00.000Z'};state.versions.push(row);return clone(row);},
    async findVersion(id){return clone(joined(state.versions.find((row)=>row.adapter_version_id===id)));},
    async findActiveBinding(clientId,target=null){const binding=[...state.bindings].reverse().find((row)=>row.integration_client_id===clientId&&row.status==='active'&&(!target||row.target_event_type===target));if(!binding)return null;const version=state.versions.find((row)=>row.adapter_version_id===binding.adapter_version_id);return clone({...binding,...joined(version)});},
    async listVersions(templateId){return clone(state.versions.filter((row)=>row.adapter_template_id===templateId).sort((a,b)=>b.version-a.version).map(joined));},
    async supersedeActive(templateId){const rows=state.versions.filter((row)=>row.adapter_template_id===templateId&&row.status==='active');rows.forEach((row)=>{row.status='superseded';});return clone(rows);},
    async activateVersion(id,actor){const row=state.versions.find((item)=>item.adapter_version_id===id&&['draft','superseded'].includes(item.status));if(!row)return null;Object.assign(row,{status:'active',activated_by:actor,activated_at:'2026-09-01T00:03:00.000Z'});return clone(joined(row));},
    async deactivateClientBinding(clientId,target){const rows=state.bindings.filter((row)=>row.integration_client_id===clientId&&row.target_event_type===target&&row.status==='active');rows.forEach((row)=>{row.status='inactive';});return clone(rows);},
    async createBinding(r){const row={adapter_binding_id:r.bindingId,integration_client_id:r.integrationClientId,target_event_type:r.targetEventType,adapter_template_id:r.templateId,adapter_version_id:r.versionId,status:'active',activated_by:r.actorReference,activated_at:'2026-09-01T00:03:00.000Z'};state.bindings.push(row);return clone(row);},
    async updateTemplateBindings(templateId,versionId,actor){const rows=state.bindings.filter((row)=>row.adapter_template_id===templateId&&row.status==='active');rows.forEach((row)=>Object.assign(row,{adapter_version_id:versionId,activated_by:actor,activated_at:'2026-09-01T00:03:00.000Z'}));return clone(rows);},
    async countBindings(templateId){return{count:state.bindings.filter((row)=>row.adapter_template_id===templateId&&row.status==='active').length};},
    async consumeSample(id){const row=state.samples.find((item)=>item.adapter_sample_id===id&&item.status==='captured');if(!row)return null;row.status='consumed';row.sample_payload=null;return{adapter_sample_id:id};},
    async upsertNotice(r){let row=state.notices.find((item)=>item.adapter_template_id===r.templateId&&item.notice_type===r.noticeType&&item.source_field_key===r.fieldKey);if(row){row.adapter_version_id=r.versionId;row.occurrence_count+=1;row.last_seen_at='2026-09-01T00:04:00.000Z';return clone(row);}row={adapter_notice_id:r.noticeId,adapter_template_id:r.templateId,adapter_version_id:r.versionId,notice_type:r.noticeType,source_field_key:r.fieldKey,source_path:r.sourcePath,value_type:r.valueType,status:'available',occurrence_count:1,first_seen_at:'2026-09-01T00:04:00.000Z',last_seen_at:'2026-09-01T00:04:00.000Z'};state.notices.push(row);return clone(row);},
    async listNotices(templateId){return clone(state.notices.filter((row)=>row.adapter_template_id===templateId&&['available','review_later'].includes(row.status)));},
    async updateNotice(templateId,noticeId,status,actor){const row=state.notices.find((item)=>item.adapter_template_id===templateId&&item.adapter_notice_id===noticeId);if(!row)return null;row.status=status;row.updated_by=actor;return clone(row);},
  };
}
module.exports={createIntegrationAdapterMemoryRepository};
