function createIntegrationEventMemoryRepository(){const state={events:[]};let tick=0;const stamp=()=>new Date(Date.UTC(2026,7,27,3,0,tick++)).toISOString();const clone=r=>r?{...r,canonical_payload:r.canonical_payload?JSON.parse(JSON.stringify(r.canonical_payload)):r.canonical_payload}:null;
  return{state,
    async insertEvent(r){if(state.events.some(x=>x.integration_client_id===r.integrationClientId&&x.external_event_id===r.externalEventId))return null;const row={integration_event_id:r.integrationEventId,integration_client_id:r.integrationClientId,organization_id:r.organizationId,external_event_id:r.externalEventId,event_type:r.eventType,payload_sha256:r.payloadSha256,canonical_payload:JSON.parse(JSON.stringify(r.canonicalPayload)),status:'received',external_center_id:r.externalCenterId,external_resident_id:r.externalResidentId,center_id:r.centerId,resident_id:null,care_profile_id:null,canonical_resource_type:null,canonical_resource_id:null,pending_reason:null,last_error_code:null,attempt_count:0,next_attempt_at:null,processed_at:null,expected_line_group_id:r.expectedLineGroupId||null,verified_line_group_id:null,group_reconciliation_status:null,notification_intent_status:null,created_at:stamp(),updated_at:stamp()};state.events.push(row);return clone(row);},
    async findByExternalId(c,e){return clone(state.events.find(x=>x.integration_client_id===c&&x.external_event_id===e));},async findEvent(id){return clone(state.events.find(x=>x.integration_event_id===id));},
    async claimEvent(id){const row=state.events.find(x=>x.integration_event_id===id);if(!row||!['received','pending','retrying','processing'].includes(row.status))return null;if(row.status==='processing'&&!row.stale)return null;if(row.next_attempt_at&&new Date(row.next_attempt_at)>new Date('2099-01-01'))return null;row.status='processing';row.attempt_count++;row.updated_at=stamp();row.stale=false;return clone(row);},
    async markPending(id,{residentId=null,careProfileId=null,reason='subject_mapping'}={}){const row=state.events.find(x=>x.integration_event_id===id);Object.assign(row,{status:'pending',resident_id:residentId,care_profile_id:careProfileId,pending_reason:reason,last_error_code:null,next_attempt_at:null,updated_at:stamp()});return clone(row);},
    async markProcessed(id,x){const row=state.events.find(e=>e.integration_event_id===id);Object.assign(row,{status:'processed',resident_id:x.residentId,care_profile_id:x.careProfileId,canonical_resource_type:x.resourceType,canonical_resource_id:x.resourceId,pending_reason:null,last_error_code:null,next_attempt_at:null,expected_line_group_id:x.expectedLineGroupId||null,verified_line_group_id:x.verifiedLineGroupId||null,group_reconciliation_status:x.groupReconciliationStatus||null,notification_intent_status:x.notificationIntentStatus||'not_applicable',processed_at:stamp(),updated_at:stamp()});return clone(row);},
    async updateRouting(id,x){const row=state.events.find(e=>e.integration_event_id===id&&e.status==='processed');if(!row)return null;Object.assign(row,{expected_line_group_id:x.expectedLineGroupId||null,verified_line_group_id:x.verifiedLineGroupId||null,group_reconciliation_status:x.groupReconciliationStatus,notification_intent_status:x.notificationIntentStatus,updated_at:stamp()});return clone(row);},
    async markRejected(id,code){const row=state.events.find(e=>e.integration_event_id===id);Object.assign(row,{status:'rejected',last_error_code:code,next_attempt_at:null,updated_at:stamp()});return clone(row);},
    async markRetry(id,{errorCode,nextAttemptAt,dead}){const row=state.events.find(e=>e.integration_event_id===id);Object.assign(row,{status:dead?'dead':'retrying',last_error_code:errorCode,next_attempt_at:dead?null:nextAttemptAt,updated_at:stamp()});return clone(row);},
    async listDue(limit=25){return state.events.filter(x=>['received','retrying'].includes(x.status)||(x.status==='processing'&&x.stale)).slice(0,limit).map(x=>({integration_event_id:x.integration_event_id}));},
    async listPending({integrationClientId=null,externalCenterId=null,externalResidentId=null,limit=50}={}){return state.events.filter(x=>x.status==='pending'&&(!integrationClientId||x.integration_client_id===integrationClientId)&&(!externalCenterId||x.external_center_id===externalCenterId)&&(!externalResidentId||x.external_resident_id===externalResidentId)).sort((a,b)=>a.created_at.localeCompare(b.created_at)).slice(0,limit).map(clone);},
    async listOperational({integrationClientId=null,organizationId=null,centerId=null,groupStatus=null,limit=100}={}){return state.events.filter(x=>(!integrationClientId||x.integration_client_id===integrationClientId)&&(!organizationId||x.organization_id===organizationId)&&(!centerId||x.center_id===centerId)&&(!groupStatus||x.group_reconciliation_status===groupStatus)).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).slice(0,limit).map(clone);},
  };}
module.exports={createIntegrationEventMemoryRepository};
